name: Debug Workflow

on:
  workflow_dispatch:

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -laR

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
