name: Test Fetch Script

on:
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the fetch script
        env:
          API_ID: ${{ secrets.API_ID }}
        run: python scripts/fetch_telegram.py > script_output.log 2>&1

      - name: Upload script output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: script-output
          path: script_output.log